'-----------------------------------------------------------------------------------  
' for the CX16
'
' COLOR CODES CONSTS
'
' sadLogic / Steve De George SR.   Nov 2025, Kherson Ukraine
' Compile with nxtBasic: https://github.com/unartic/nxtBasic   Windows - CRLF
'-----------------------------------------------------------------------------------

CONST cCOLOR_BLACK = 0
CONST cCOLOR_WHITE = 1
CONST cCOLOR_RED = 2
CONST cCOLOR_CYAN = 3
CONST cCOLOR_PURPLE  = 4
CONST cCOLOR_GREEN = 5
CONST cCOLOR_BLUE = 6
CONST cCOLOR_YELLOW = 7
CONST cCOLOR_ORANGE = 8
CONST cCOLOR_BROWN = 9
CONST cCOLOR_LIGHT_RED = 10
CONST cCOLOR_DARK_GRAY = 11
CONST cCOLOR_GRAY = 12
CONST cCOLOR_LIGHT_GREEN = 13
CONST cCOLOR_LIGHT_BLUE = 14
CONST cCOLOR_LIGHT_GRAY = 15


