'-------------------------------------------------------------------------------  
' for the CX16
'
' 
'
' sadLogic / Steve De George SR. / Steve De George JR
' Compile with nxtBasic: https://github.com/unartic/nxtBasic   Windows - CRLF
'-----------------------------------------------------------------------------------

SUB DOS_DelFolder

END SUB


SUB DOS_RenameFolder

END SUB



SUB DOS_DelFile

END SUB 
SUB DOS_RenameFile

END SUB
SUB DOS_GetFileInfo

END SUB

SUB DOS_GetFolderInfo

END SUB
SUB DOS_CreateFolder

END SUB 


